### ISSUE TITLE
Tight coupling to the Gordian Envelope API

### ISSUE THREAD

**Issue by cyberphone** [BlockchainCommons/WIPs-IETF-draft-deterministic-cbor#3]
Friendly advice, not a requirement.

I have only skimmed the code but this line
https://github.com/BlockchainCommons/BCSwiftEnvelope/blob/master/Tests/EnvelopeTests/GraphTests.swift#L13
indicates that the GE API (effectively) is tightly coupled to dCBOR.

I would revisit the current approach for custom data like assertions for a future release.  Maybe using something along these lines:

```code
var builder = new XYZBuilder()
    .setType(THINGIE)
    .setDate(today)
       -
       -
       -
    .setSomething(something);

var doc = builder.create();
``` 

In addition to enabling compile-time method and argument checking, this {c|w}ould also make the GE API independent of CBOR encoding scheme.

I guess one problem is that assertions are community specific?  It seems to me that an organization creating a community profile must also (in some way...) deal with the custom API and CBOR key value assignments.

**Comment by wolfmcnally** [comment]
Yes, the Envelope API is tightly bound to dCBOR, because the LEAF case MUST be dCBOR and envelopes themselves are always dCBOR. However, this does not mean you can't easily compose envelopes with a non-dCBOR API.

Please see our Research repo for several specs that define specific assertions for use with specific envelope-based specifications.
