### ISSUE TITLE
Duplicate map example somewhat confusing

### ISSUE THREAD

**Issue by cabo** [BlockchainCommons/WIPs-IETF-draft-deterministic-cbor#5]
```
{
   10: "ten",
   10.0: "floating ten"
}
```

already is invalid dCBOR because 10.0 is invalid dCBOR.
I think we need to be more careful with distinguishing what is interchanged (which can be written in cbor-diag) and what the application feeds into an encoder.

**Comment by wolfmcnally** [comment]
I have modified the language in the I-D to read:

Note that numeric reduction means that some valid CDE/CBOR maps are not valid dCBOR maps, as numeric reduction can result in duplicate keys. For example, the following is a valid CBOR/CDE map, but would be rejected as invalid by a dCBOR decoder because the value `10.0` is not a valid dCBOR encoding:

~~~ cbor-diag
{
  10: "ten",
  10.0: "floating ten"
}
~~~
